// Code generated by hertz generator.

package sandbox

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sandboxMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdemoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postdemoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sandbox0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putdemoMw() []app.HandlerFunc {
	// your code...
	return nil
}
