// Code generated by hertz generator.

package sandbox

import (
	"dolphin-sandbox/biz/dal"
	"dolphin-sandbox/biz/mw"
	"dolphin-sandbox/conf"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	var funcs = []app.HandlerFunc{
		mw.MaxWorker(conf.GetConf().Sandbox.MaxWorkers, mw.AllowPathPrefixSkipper(dal.NoLogin...)),
		mw.MaxRequest(conf.GetConf().Sandbox.MaxRequests, mw.AllowPathPrefixSkipper(dal.NoLogin...)),
	}
	// your code...
	return funcs
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sandboxMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdemoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postdemoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sandbox0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putdemoMw() []app.HandlerFunc {
	// your code...
	return nil
}
