// Code generated by hertz generator.

package main

import (
	Cmd "dolphin-sandbox/cmd"
	"dolphin-sandbox/cmd/srv_http"
	"fmt"
	"os"
)

//	@title			Dolphin-Sandbox API
//	@version		1.0
//	@description	Dolphin-Sandbox 提供了一种在安全环境中运行不可信代码的简单方式。它适用于多租户场景，允许多个用户提交代码进行执行。代码将在受限的沙箱环境中运行，限制其可访问的资源和系统调用。
//	@description	Authorization Bearer token
//	@description	Header:  x-enc-data = yes

//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@schema						Bearer

//	@contact.name	aigc
//	@contact.url	https://github.com/v-mars/dolphin-dandbox
//
// //@host        localhost:8200
//
//	// @BasePath /
//
// //@schemes     http
func main() {
	//dal.Init()

	srv_http.RootCmd.AddCommand(Cmd.Version())
	if err := srv_http.RootCmd.Execute(); err != nil {
		_ = fmt.Errorf("rootCmd.Execute failed %s", err.Error())
		os.Exit(-1)
	}
}
