// Code generated by hertz generator.

package main

import (
	"dolphin-sandbox/cmd/srv_http"
	_ "dolphin-sandbox/docs"
)

//	@title			Dolphin Sandbox API
//	@version		1.0
//	@description	Authorization Bearer token
//	@description	header:  x-enc-data = yes

//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@schema						Bearer

//	@contact.name	Dolphin Sandbox
//	@contact.url
//
// //@host        localhost:8162
//
//	// @BasePath /
//
// //@schemes     http
func main() {
	srv_http.Start()
}
