// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	//c.GetRequest().Header.RawHeaders()
	hlog.Info(string(c.Request.Header.RawHeaders()))
	//c.SetBodyString("set body data")
	c.JSON(consts.StatusOK, utils.H{
		"message":         "pong",
		"request header":  string(c.Request.Header.RawHeaders()),
		"response header": string(c.Response.Header.Header()),
		"body":            string(c.Response.BodyBytes()),
	})
}

func Health(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, "ok")
}
