// Code generated by hertz generator.

package sandbox

import (
	"context"

	sandbox "dolphin-sandbox/kitex_gen/sandbox"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetDemo .
// @router /api/sandbox/run [GET]
func GetDemo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sandbox.DemoQuery
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(sandbox.DemoResp)

	c.JSON(consts.StatusOK, resp)
}

// PostDemo .
// @router /api/sandbox/run [POST]
func PostDemo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sandbox.DemoPost
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(sandbox.DemoResp)

	c.JSON(consts.StatusOK, resp)
}

// PutDemo .
// @router /api/v1/sandbox/run [PUT]
func PutDemo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sandbox.DemoPut
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(sandbox.DemoResp)

	c.JSON(consts.StatusOK, resp)
}
