// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	api "dolphin-sandbox/biz/router/api"
	base "dolphin-sandbox/biz/router/base"
	sandbox "dolphin-sandbox/biz/router/sandbox"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	sandbox.Register(r)

	api.Register(r)

	base.Register(r)
}
